import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { compileGraphSuite, exportGraphSuite } from "../src/graph.js";

const cleanup: Array<() => void> = [];
const exampleGraph = resolve(process.cwd(), "examples/graphs/appointment-cancellation.yaml");

afterEach(() => {
  while (cleanup.length) cleanup.pop()?.();
});

describe("conversation graph CLI helpers", () => {
  it("compiles named runs into labeled flat scenarios", async () => {
    const compiled = await compileGraphSuite({ graphPath: exampleGraph, runs: ["smoke"] });
    expect(compiled).toHaveLength(2);
    expect(compiled[0].scenario.name).toContain("Appointment cancellation");
    expect(compiled.map((item) => item.pathName).sort()).toEqual(["cancellation_success", "identity_retry"]);
    expect(compiled[0].label).toContain(exampleGraph);
  });

  it("writes explicit flat YAML exports only when requested", async () => {
    const directory = mkdtempSync(join(tmpdir(), "agentphone-graph-export-"));
    cleanup.push(() => rmSync(directory, { recursive: true, force: true }));

    const written = await exportGraphSuite({ graphPath: exampleGraph, runs: ["smoke"] }, directory);
    expect(written).toHaveLength(2);
    const yaml = readFileSync(written[0], "utf8");
    expect(yaml).toContain("# Generated by AgentPhone DevTools");
    expect(yaml).toContain("turns:");
    expect(yaml).toContain("I need to cancel my appointment.");
  });
});
